version: "3.9"
services:
  app:
    build: .
    container_name: game
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    ports:
      - "8090:8080"
    networks:
      - app-network
  postgres:
    image: postgres:14.9
    container_name: postgres
    environment:
      - POSTGRES_DB=GAME
      - POSTGRES_USER=GAME
      - POSTGRES_PASSWORD=GAME
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
